name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: Build the app
        run:  ./scripts/buildprod.sh
            
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'gcloud submit'
        run: 'gcloud builds submit --tag us-east1-docker.pkg.dev/vital-pillar-440113-s6/notely-ar-repo/642b5302a928:latest .'
      
      - name: 'Deploy to Cloud Run'
        run: 'gcloud run deploy notely --image us-east1-docker.pkg.dev/vital-pillar-440113-s6/notely-ar-repo/642b5302a928:latest --region us-central1 --allow-unauthenticated --project vital-pillar-440113-s6 --max-instances=4'
